### ISSUE TITLE
close() command hanging

### ISSUE THREAD

**Issue by jadcsi** [profesorfalken/jPowerShell#1] opened 2016-02-25 19:17 UTC
My code involves executing 2 Powershell commands in a session and then closing the powershell object.   $PSVersionTable.PSVersion is:

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

Problem is that the close() hangs

**Comment by profesorfalken** [comment] 2016-02-25 19:55
Hello. Thank you for your feedback.

In order to fix it I will need more details:
-Windows version
-What kind of powershell commands are you trying to execute?
-Does it work if you perform a execute two executeSingleCommand?

Thanks

**Comment by jadcsi** [comment] 2016-02-25 21:32
OS is Windows Server 2012 R2 Standard 64 bit and java version is 1.8

It wouldn't work if I ran it as 2 executeSingleCommand

1st command is: Import-Module to a psm1 file
2nd command is: Convert-DocxToHtml which is a method from the library imported

**Comment by profesorfalken** [comment] 2016-02-26 10:54
Ok, and the problem is that the close() hangs? The Convert-DocxToHtml is correctly executed and it does its job? You have no logs from the library of type "timeout"?

Thank you

**Comment by jadcsi** [comment] 2016-02-26 16:58
This is also happening when I execute your example:

       powerShell = PowerShell.openSession();
       PowerShellResponse response = powerShell.executeCommand("Get-Process");
       response = powerShell.executeCommand("Get-WmiObject Win32_BIOS");

Somehow maybe whenever we are executing more than one command.

**Comment by profesorfalken** [comment] 2016-02-26 17:23
> This is also happening when I execute your example:
Yes, but in my systems (Windows XP and Windows 7) it works and all the tests pass.

For that reason I would need more feedback of your problem. 

I will try to reformulate the same questions I did in the last post:
-Does it hangs in the close()? or in the executeCommand()?
-The commands are executed correctly anyway before hanging?
-Nothing in the logs?

Thanks

**Comment by jadcsi** [comment] 2016-02-26 18:32
It hangs in the close() and the command are executed correctly before hanging.

I am running it in debug mode in Eclipse and below are the lines executed for the close():

ln 141
ln 143
ln 151
ln 152
ln 163
ln 164
ln 165
ln 167
ln 171
ln 174 and it stays stuck here

**Comment by profesorfalken** [comment] 2016-02-26 18:37
Cool, thank you. I will keep you updated.

**Comment by profesorfalken** [comment] 2016-02-26 19:59
Apparently in your system the close() is not able to close correctly all the threads used by the pool. 

I have created a new branch to fix it. You can already download the snapshot version here: https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.1-SNAPSHOT/jPowerShell-1.3.1-20160226.195542-2.jar

Can you check I it works now and, if not, what is the output?

Thank you

**Comment by jadcsi** [comment] 2016-02-26 20:17
It is still hanging unfortunately with the new snapshot version.  You can see its getting to the last curly brace of the java method and then hanging.  There appears to be 3 threads tied to it in the Java Debugger as you can see from the Debugger screenshot:

![hang](https://cloud.githubusercontent.com/assets/13354367/13364257/ae7f34a2-dc82-11e5-9c53-61e70255a414.png)

**Comment by profesorfalken** [comment] 2016-02-26 20:33
And no logs? It is strange... I have added a lot of more code to locate&fix it.

Could you test it please? 

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.1-SNAPSHOT/jPowerShell-1.3.1-20160226.195542-3.jar

Thanks

**Comment by jadcsi** [comment] 2016-02-26 20:39
No logs.  I am getting a 404 for your new link

**Comment by profesorfalken** [comment] 2016-02-26 20:40
Good link: 
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.1-SNAPSHOT/jPowerShell-1.3.1-20160226.203036-3.jar

**Comment by jadcsi** [comment] 2016-02-26 20:45
Tested it and the only log message was this:

Feb 26, 2016 3:44:25 PM com.profesorfalken.jpowershell.PowerShell close
INFO: Closing powerShell session...

**Comment by profesorfalken** [comment] 2016-02-26 21:07
I have cancel the threads manually after use them. Can you try please?

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.1-SNAPSHOT/jPowerShell-1.3.1-20160226.210511-4.jar

**Comment by jadcsi** [comment] 2016-02-26 22:45
It is still hanging but below are the logs:

Feb 26, 2016 5:43:30 PM com.profesorfalken.jpowershell.PowerShell close
INFO: Closing powerShell session...
Feb 26, 2016 5:43:30 PM com.profesorfalken.jpowershell.PowerShell close
INFO: ThreadPool going to shut down...
Feb 26, 2016 5:43:30 PM com.profesorfalken.jpowershell.PowerShell close
INFO: ThreadPool shutted down...
Feb 26, 2016 5:43:30 PM com.profesorfalken.jpowershell.PowerShell close
INFO: Its done

**Comment by profesorfalken** [comment] 2016-02-27 16:28
Good news. After many tries I have reproduced it!

I will post here when fixed

**Comment by profesorfalken** [comment] 2016-02-27 16:54
Done. The thread pool was initiliazed in the wrong place.

I have pushed the new 1.3.1 version with the fix but it will take several hours to be available on Maven Central.

Alternatively, you can already download the JAR file here:
https://oss.sonatype.org/content/groups/staging/com/profesorfalken/jPowerShell/1.3.1/jPowerShell-1.3.1.jar

Please, can you confirm that it works and I close the issue?

Thanks for your help.

**Comment by jadcsi** [comment] 2016-02-27 17:31
Woohoo!! It works.

I even tested with my previous commands.  I wish I could pay you back or
get you a drink.

**Comment by profesorfalken** [comment] 2016-02-27 18:26
Great news! The world is small, who knows if one day :-) 

Thanks to you for helping me to locate the error.

I close this issue.

**Closed** 2016-02-27 18:26 UTC
