### ISSUE TITLE
Hanging in Close() returns in V 1.4

### ISSUE THREAD

**Issue by jadcsi** [profesorfalken/jPowerShell#4] opened 2016-03-14 17:56 UTC
The issue I reported in the past returns in the newest version 1.4

All works well however when I switch back to v 1.3.1

**Comment by profesorfalken** [comment] 2016-03-14 19:03
Hello, 

It is extrange since I cannot reproduce it this time. 

In version 1.4 I have only done code refactoring but I changed nothing.

Do you have the problem with 1.3.2 or 1.3.3?

What is you exact test code?

Thank you!

**Comment by jadcsi** [comment] 2016-03-14 19:40
This is happening on line 159 of PowerShell.class:

                    while (!this.threadpool.isTerminated()) {


Prior to this hanging, my executeCommand method failed:

Mar 14, 2016 3:34:26 PM com.profesorfalken.jpowershell.PowerShell
executeCommand
SEVERE: Unexpected error when processing PowerShell command
java.util.concurrent.ExecutionException: java.io.IOException: The parameter
is incorrect
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShell.executeCommand(PowerShell.java:122)

The CmdLet I call through Powershell is error prone and my script would
repeatedly execute it until it works.  In version 1.3.1 close() was not
hanging

**Comment by profesorfalken** [comment] 2016-03-14 20:06
Interesting...

In the stacktrace, do you have a 'caused by:' line? Could you provide the full stacktrace?

I could have broken it with the refactoring I have done for 1.4 or with the fix for 1.3.3.
Could you please check if the 1.3.3 version works for you? That will help me a lot in order to locate the problem.

Thanks

**Comment by jadcsi** [comment] 2016-03-14 20:21
Yes its happening with 1.3.3 as well.  Below is the full stack trace until
proprietary code is reached:

Mar 14, 2016 4:17:55 PM com.profesorfalken.jpowershell.PowerShell
executeCommand
SEVERE: Unexpected error when processing PowerShell command
java.util.concurrent.ExecutionException: java.io.IOException: The parameter
is incorrect
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShell.executeCommand(PowerShell.java:124)
...
Caused by: java.io.IOException: The parameter is incorrect
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(Unknown Source)
at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
at sun.nio.cs.StreamDecoder.read(Unknown Source)
at java.io.InputStreamReader.read(Unknown Source)
at java.io.BufferedReader.fill(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:67)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:34)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Mar 14, 2016 4:17:55 PM com.profesorfalken.jpowershell.PowerShell
executeCommand
SEVERE: Unexpected error when processing PowerShell command
java.util.concurrent.ExecutionException: java.io.IOException: The parameter
is incorrect
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShell.executeCommand(PowerShell.java:124)
at
...
Caused by: java.io.IOException: The parameter is incorrect
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(Unknown Source)
at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
at sun.nio.cs.StreamDecoder.read(Unknown Source)
at java.io.InputStreamReader.read(Unknown Source)
at java.io.BufferedReader.fill(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:67)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:34)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by profesorfalken** [comment] 2016-03-14 20:49
Wow I am really puzzled for this problem.

In your use case, do you create a lot of different jPowershell sessions? do you create them in parallel? Do you launch many commands in the same session?

Thanks for your help

**Comment by jadcsi** [comment] 2016-03-14 20:56
Yes my script is basically opening a new session for each file it needs to
process.  Think of it as a pipeline that converts docx files to html using
a Powershell CmdLet.  They are not in parallel but in sequence and each
session is 2 commands: one to load the library and the second to execute
the conversion.

**Comment by profesorfalken** [comment] 2016-03-15 18:51
Hi, 

Could you please test if this snapshot fix your problem?

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.4.1-SNAPSHOT/jPowerShell-1.4.1-20160315.184951-1.jar

Thank you again :-)

**Comment by jadcsi** [comment] 2016-03-15 19:25
Just tested it and unfortunately hanging each time after this error is
shown:

Mar 15, 2016 3:23:57 PM
com.profesorfalken.jpowershell.PowerShellCommandProcessor call
SEVERE: Unexpected error reading PowerShell output
java.io.IOException: The parameter is incorrect
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(Unknown Source)
at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
at sun.nio.cs.StreamDecoder.read(Unknown Source)
at java.io.InputStreamReader.read(Unknown Source)
at java.io.BufferedReader.fill(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.readData(PowerShellCommandProcessor.java:79)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:66)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:33)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Mar 15, 2016 3:23:57 PM
com.profesorfalken.jpowershell.PowerShellCommandProcessor call
SEVERE: Unexpected error reading PowerShell output
java.io.IOException: The parameter is incorrect
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(Unknown Source)
at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
at sun.nio.cs.StreamDecoder.read(Unknown Source)
at java.io.InputStreamReader.read(Unknown Source)
at java.io.BufferedReader.fill(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at java.io.BufferedReader.readLine(Unknown Source)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.readData(PowerShellCommandProcessor.java:79)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:66)
at
com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:33)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by profesorfalken** [comment] 2016-03-16 20:17
Hi, 

I have built a version that changes the way os closing the threadpool and adds lots of logs.
Could you give it a try and tell me what it returns?

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.4.1-SNAPSHOT/jPowerShell-1.4.1-20160316.201134-2.jar


Thanks!

**Comment by jadcsi** [comment] 2016-03-16 20:48
Thanks for that, this version is very robust!! I tested it twice and
despite failures with the CmdLet calls, it was able to close the session
without hanging.  Thanks again for your splendid work!!

**Comment by profesorfalken** [comment] 2016-03-16 21:44
Great news! I will prepare the v1.4.1

This small tool is getting more an more robust thanks to your help.
I close this issue then. Thank a lot!

**Closed by profesorfalken** 2016-03-16 21:44 UTC
